# This is a basic workflow to help you get started with Actions

name: Sign image (avbtool)

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      IMAGE_URL:
        description: 'URL of the image you want to sign'
        required: true
        default: ''
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Prepare envionment
        run: |
          git clone https://github.com/SebaUbuntu/AIK-Linux-mirror aik
          sudo apt install python3 -y

      - name: Debug
        uses: mxschmitt/action-tmate@v3

      - name: Force stop
        run: fuckyou

      - name: Get image
        run: wget ${{ github.event.inputs.IMAGE_URL }} -O ./aik/1.img

      - name: Remove invalid content in your image
        run: |
          ./unpackimg.sh 1.img
          ./repackimg.sh
          cp -v image-new.img ../legacy/out.img
        working-directory: aik
        

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Signed image
          path: 'legacy/out-sign.img'
